"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FORMAT_CODE_EXTENSION = exports.REQUEST_TIMEOUT = exports.UNKNOWN_GROUP_DESC = exports.UNKNOWN_GROUP_NAME = exports.COMMENT_END_CODE = exports.COMMENT_START_CODE = exports.LINE_FEED_CODE_MAC = exports.LINE_FEED_CODE = void 0;
exports.LINE_FEED_CODE = String.fromCharCode(62100);
exports.LINE_FEED_CODE_MAC = String.fromCharCode(62101);
exports.COMMENT_START_CODE = String.fromCharCode(62200);
exports.COMMENT_END_CODE = String.fromCharCode(62300);
exports.UNKNOWN_GROUP_NAME = '未知分组';
exports.UNKNOWN_GROUP_DESC = '未设置分组的接口集合';
exports.REQUEST_TIMEOUT = 120000;
exports.FORMAT_CODE_EXTENSION = ['.ts', '.tsx', '.js', '.jsx', '.vue', '.html', '.scss', '.less', '.css', '.json', '.java'];
