import { APIHelper } from '@api-helper/core/es/lib/types';

export const DOCUMENT: APIHelper.Document = {
  id: 'a91a551c-59d4-460a-a506-3f168a359bab',
  title: '接口文档',
  description: '测试API示例项目',
  version: '0.0.1-SNAPSHOT',
  openapiVersion: '2.0',
  basePath: '/api',
  categoryList: [{
    id: '04c71159-7e10-499d-8adb-8ed94e8a11dd',
    name: '宠物店认证模块',
    description: 'Tenant Controller',
    apiList: [{
      id: '15f5f834-d3e3-43eb-bd87-24fe73d2cdbc',
      title: '账户登录',
      description: '账户登录',
      label: '账户登录',
      path: '/api/tenant/auth',
      method: 'post',
      formDataKeyNameList: [],
      pathParamKeyNameList: [],
      queryStringKeyNameList: [],
      requestDataSchema: {
        id: '3caa4e71-ec36-48ac-ad8b-9d310d4379e8',
        type: 'object',
        keyName: '',
        title: '',
        description: '',
        label: '',
        rules: { required: false },
        examples: [],
        params: [{
          id: '9d666d9a-d826-408c-bb0c-94110eb35c88',
          title: '',
          description: '图形验证码结果',
          label: '图形验证码结果',
          keyName: 'code',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: '78e3a579-3a39-4881-b154-8a5af471c5a0',
          title: '',
          description: '认证类型',
          label: '认证类型',
          keyName: 'grant_type',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: '592e522c-8da6-4d0c-b0d1-0b5ec9dfe00d',
          title: '',
          description: '密码密文(认证类型password必传)',
          label: '密码密文(认证类型password必传)',
          keyName: 'password',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: 'db116961-9587-4f63-9198-a274fb1b9ff1',
          title: '',
          description: '手机号',
          label: '手机号',
          keyName: 'phone',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: 'd16ab951-dd78-4640-9241-b3c351c824f1',
          title: '',
          description: '授权范围，默认填all',
          label: '授权范围，默认填all',
          keyName: 'scope',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: 'cf631075-4db9-4393-ac09-5568fea127ac',
          title: '',
          description: '短信验证码结果',
          label: '短信验证码结果',
          keyName: 'smsCode',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: 'd6003c37-d352-4401-af47-930dad009361',
          title: '',
          description: '登录机构ID',
          label: '登录机构ID',
          keyName: 'tenantId',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: '29d8fa6c-9151-4333-9ded-046e08b4354e',
          title: '',
          description: '账户名',
          label: '账户名',
          keyName: 'username',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }, {
          id: '25f9df07-38c8-4ebb-96af-a006568a473f',
          title: '',
          description: '图形验证码key',
          label: '图形验证码key',
          keyName: 'uuid',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: false },
        }],
      },
      requestExtraDataSchema: null,
      responseDataSchema: {
        id: '6221bd86-0aed-4027-89e7-58f8b69e25c0',
        title: '统一响应消息报文«TokenResponseVO»',
        description: '',
        label: '统一响应消息报文«TokenResponseVO»',
        keyName: '',
        type: 'object',
        params: [{
          id: '9c587097-9425-4311-9bc0-af22664c9ea7',
          title: '',
          description: '状态码',
          label: '状态码',
          keyName: 'code',
          type: 'number',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '8b625667-b88a-4105-bf9a-915ac2a9f878',
          title: 'TokenResponseVO',
          description: '业务数据',
          label: 'TokenResponseVO',
          keyName: 'data',
          type: 'object',
          params: [{
            id: 'd2c5f2c3-49e5-4a1a-a993-504915e521c8',
            title: '',
            description: '授权令牌',
            label: '授权令牌',
            keyName: 'accessToken',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '12eafdd7-bd39-4ccf-87c6-9423b65e2b4d',
            title: '',
            description: '当前登录机构ID',
            label: '当前登录机构ID',
            keyName: 'currentTenant',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '5d560a30-c068-43eb-ad71-44d227e146bf',
            title: '',
            description: '账户昵称',
            label: '账户昵称',
            keyName: 'nickName',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '476adde7-10a7-44f9-ab85-481e1e7fd1f5',
            title: '',
            description: '权限集合,登录成功返回',
            label: '权限集合,登录成功返回',
            keyName: 'permissions',
            type: 'array',
            params: [{
              id: 'a022fdd5-d053-4eac-b918-29e723878579',
              title: '',
              description: '',
              label: '',
              keyName: '',
              type: 'string',
              params: [],
              examples: [],
              rules: { required: true },
            }],
            examples: [],
            rules: { required: true },
          }, {
            id: '42b314b3-17b5-45f6-853b-dc18455842be',
            title: '',
            description: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            label: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            keyName: 'submitToken',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: 'b73a79f3-a6ef-4120-acea-d56a14ef0eee',
            title: '',
            description: '账户关联机构',
            label: '账户关联机构',
            keyName: 'tenants',
            type: 'array',
            params: [{
              id: '51c3a0fb-e4e4-4012-a56c-ed026ccebc48',
              title: 'TenantBO',
              description: '',
              label: 'TenantBO',
              keyName: '',
              type: 'object',
              params: [{
                id: '12391411-5851-4172-8b3c-d517ff3febe4',
                title: '',
                description: '',
                label: '',
                keyName: 'id',
                type: 'number',
                params: [],
                examples: [],
                rules: { required: true },
              }, {
                id: 'd8887740-74d0-49ab-90df-f8dac553aa4b',
                title: '',
                description: '',
                label: '',
                keyName: 'lastLoginTime',
                type: 'string',
                params: [],
                examples: [],
                rules: { required: true },
              }, {
                id: '4bd87933-3ca2-416e-b9c2-9c64d68e61a7',
                title: '',
                description: '',
                label: '',
                keyName: 'tenantCode',
                type: 'string',
                params: [],
                examples: [],
                rules: { required: true },
              }, {
                id: 'c01066fd-b883-4983-89b5-abb02d1c6007',
                title: '',
                description: '',
                label: '',
                keyName: 'tenantName',
                type: 'string',
                params: [],
                examples: [],
                rules: { required: true },
              }],
              examples: [],
              rules: { required: true },
            }],
            examples: [],
            rules: { required: true },
          }, {
            id: 'b48959f6-101e-4a87-9258-314d80e820c7',
            title: '',
            description: '登录类型，1：账号密码，2：短信验证码',
            label: '登录类型，1：账号密码，2：短信验证码',
            keyName: 'type',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: 'b0156f4c-73a7-4731-8158-4d4bb4fa9e75',
            title: '',
            description: '账户ID',
            label: '账户ID',
            keyName: 'userId',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '43f4a96b-a1db-438a-aa21-6bebb219c4ba',
            title: '',
            description: '账户类型，0：管理用户，1：机构用户',
            label: '账户类型，0：管理用户，1：机构用户',
            keyName: 'userType',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '23956572-8555-4e2a-ad22-b499b8b9ef83',
            title: '',
            description: '账户名',
            label: '账户名',
            keyName: 'username',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }],
          examples: [],
          rules: { required: true },
        }, {
          id: 'e99f3a8e-778e-48be-894d-abebc88d121a',
          title: '',
          description: '消息内容',
          label: '消息内容',
          keyName: 'msg',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '13240ac1-46d3-40f7-88a5-8cf7d4825ec4',
          title: '',
          description: '',
          label: '',
          keyName: 'success',
          type: 'boolean',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '693e5334-5614-4097-9755-d2fed0b7d4d6',
          title: '',
          description: '时间戳',
          label: '时间戳',
          keyName: 'time',
          type: 'number',
          params: [],
          examples: [],
          rules: { required: true },
        }],
        examples: [],
        rules: { required: true },
      },
    }, {
      id: '25a4f5df-573d-4be0-9b8d-ce4661413de9',
      title: '登录确认',
      description: '登录确认',
      label: '登录确认',
      path: '/api/tenant/auth',
      method: 'get',
      formDataKeyNameList: [],
      pathParamKeyNameList: [],
      queryStringKeyNameList: ['tenantId', 'submitToken'],
      requestDataSchema: {
        id: '35bbe5c9-94cb-41cf-939a-c98affeeb8fb',
        type: 'object',
        keyName: '',
        title: '',
        description: '',
        label: '',
        rules: { required: false },
        examples: [],
        params: [{
          examples: [],
          id: '47352511-f752-4e7b-9e64-7f8c9ee228c0',
          title: '',
          description: '登录机构ID',
          label: '登录机构ID',
          type: 'string',
          keyName: 'tenantId',
          params: [],
          rules: { required: true },
        }, {
          examples: [],
          id: 'cd2f8c12-d12f-46ca-8866-9db1760ffc73',
          title: '',
          description: '登录确认令牌',
          label: '登录确认令牌',
          type: 'string',
          keyName: 'submitToken',
          params: [],
          rules: { required: true },
        }],
      },
      requestExtraDataSchema: null,
      responseDataSchema: {
        id: '51ff2e4c-ac75-45e7-a26a-2203df20dae0',
        title: '统一响应消息报文«TokenResponseVO»',
        description: '',
        label: '统一响应消息报文«TokenResponseVO»',
        keyName: '',
        type: 'object',
        params: [{
          id: '336cdce0-6ff8-4487-86a3-af7344ae5f53',
          title: '',
          description: '状态码',
          label: '状态码',
          keyName: 'code',
          type: 'number',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '22fef2fb-bbca-4cc4-bdec-34630709b63f',
          title: 'TokenResponseVO',
          description: '业务数据',
          label: 'TokenResponseVO',
          keyName: 'data',
          type: 'object',
          params: [{
            id: 'ed2450a2-8d4b-4306-88d5-123b0869bc4a',
            title: '',
            description: '授权令牌',
            label: '授权令牌',
            keyName: 'accessToken',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: 'cd23e394-7aee-4b4f-bf14-17d3e5d522b5',
            title: '',
            description: '当前登录机构ID',
            label: '当前登录机构ID',
            keyName: 'currentTenant',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '278fe2fe-7b30-45fe-809e-bcb7d6837dd9',
            title: '',
            description: '账户昵称',
            label: '账户昵称',
            keyName: 'nickName',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '6742a179-15ec-49f6-9aab-2da137485efe',
            title: '',
            description: '权限集合,登录成功返回',
            label: '权限集合,登录成功返回',
            keyName: 'permissions',
            type: 'array',
            params: [{
              id: 'b3a4a783-f907-4c6b-8f1c-93784cac82fb',
              title: '',
              description: '',
              label: '',
              keyName: '',
              type: 'string',
              params: [],
              examples: [],
              rules: { required: true },
            }],
            examples: [],
            rules: { required: true },
          }, {
            id: '54f99d08-bf2d-4390-8ff7-4d28edafac5a',
            title: '',
            description: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            label: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            keyName: 'submitToken',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '6ae81ebe-d4f2-4970-8efe-a24060d8c19f',
            title: '',
            description: '账户关联机构',
            label: '账户关联机构',
            keyName: 'tenants',
            type: 'array',
            params: [{
              id: 'd62f6c36-f723-4da1-8752-0c7f20fcf0d9',
              title: 'TenantBO',
              description: '',
              label: 'TenantBO',
              keyName: '',
              type: 'object',
              params: [{
                id: '479726fc-e2eb-4faf-aea7-b0f895e1ead7',
                title: '',
                description: '',
                label: '',
                keyName: 'id',
                type: 'number',
                params: [],
                examples: [],
                rules: { required: true },
              }, {
                id: '5f34e03c-8ce6-40c1-8ad4-474111e8b1f6',
                title: '',
                description: '',
                label: '',
                keyName: 'lastLoginTime',
                type: 'string',
                params: [],
                examples: [],
                rules: { required: true },
              }, {
                id: '8dcb806e-a901-4383-bb67-362e8cda6bac',
                title: '',
                description: '',
                label: '',
                keyName: 'tenantCode',
                type: 'string',
                params: [],
                examples: [],
                rules: { required: true },
              }, {
                id: '3608d837-e284-4c5f-8286-c4bddb0b3d82',
                title: '',
                description: '',
                label: '',
                keyName: 'tenantName',
                type: 'string',
                params: [],
                examples: [],
                rules: { required: true },
              }],
              examples: [],
              rules: { required: true },
            }],
            examples: [],
            rules: { required: true },
          }, {
            id: '21fa39db-f411-4f3d-a35a-3273225ed606',
            title: '',
            description: '登录类型，1：账号密码，2：短信验证码',
            label: '登录类型，1：账号密码，2：短信验证码',
            keyName: 'type',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '52d7951a-b954-4e75-a382-c70763ff9360',
            title: '',
            description: '账户ID',
            label: '账户ID',
            keyName: 'userId',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: '77f43486-7f59-46de-b188-096fc22d8e78',
            title: '',
            description: '账户类型，0：管理用户，1：机构用户',
            label: '账户类型，0：管理用户，1：机构用户',
            keyName: 'userType',
            type: 'number',
            params: [],
            examples: [],
            rules: { required: true },
          }, {
            id: 'dc009ec7-3367-44db-8603-ec32188a5aaa',
            title: '',
            description: '账户名',
            label: '账户名',
            keyName: 'username',
            type: 'string',
            params: [],
            examples: [],
            rules: { required: true },
          }],
          examples: [],
          rules: { required: true },
        }, {
          id: '2aa8446c-56c6-4b1c-93a0-39922f977642',
          title: '',
          description: '消息内容',
          label: '消息内容',
          keyName: 'msg',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: 'ae5c674d-d019-4e50-a0dc-07e1157c6085',
          title: '',
          description: '',
          label: '',
          keyName: 'success',
          type: 'boolean',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '99446a7f-67c4-4515-8da4-be61ef7bf949',
          title: '',
          description: '时间戳',
          label: '时间戳',
          keyName: 'time',
          type: 'number',
          params: [],
          examples: [],
          rules: { required: true },
        }],
        examples: [],
        rules: { required: true },
      },
    }, {
      id: '681ca845-cc6d-41b8-a7ce-f9c66ce595e7',
      title: '手机验证码获取',
      description: '手机验证码获取',
      label: '手机验证码获取',
      path: '/api/tenant/auth/verification-code',
      method: 'get',
      formDataKeyNameList: [],
      pathParamKeyNameList: [],
      queryStringKeyNameList: ['code', 'phone', 'uuid'],
      requestDataSchema: {
        id: 'f6ad4d47-1c86-4163-b327-2975ab37a4b7',
        type: 'object',
        keyName: '',
        title: '',
        description: '',
        label: '',
        rules: { required: false },
        examples: [],
        params: [{
          examples: [],
          id: 'ca196b90-32d8-4d33-b5cd-68baa903ded6',
          title: '',
          description: '图形验证码值',
          label: '图形验证码值',
          type: 'string',
          keyName: 'code',
          params: [],
          rules: { required: true },
        }, {
          examples: [],
          id: 'cb28fbb6-4e9d-4a1f-8646-9b1c933d1250',
          title: '',
          description: '手机号',
          label: '手机号',
          type: 'string',
          keyName: 'phone',
          params: [],
          rules: { required: true },
        }, {
          examples: [],
          id: '2e600944-d2bb-4a42-b158-9b8a06d75ae5',
          title: '',
          description: '图形验证码ID',
          label: '图形验证码ID',
          type: 'string',
          keyName: 'uuid',
          params: [],
          rules: { required: true },
        }],
      },
      requestExtraDataSchema: null,
      responseDataSchema: {
        id: '30685382-01ed-4370-827a-189fa58eacca',
        title: '统一响应消息报文«Void»',
        description: '',
        label: '统一响应消息报文«Void»',
        keyName: '',
        type: 'object',
        params: [{
          id: '16b127a5-8760-4e67-86af-64a905381fad',
          title: '',
          description: '状态码',
          label: '状态码',
          keyName: 'code',
          type: 'number',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '47ffc45e-e7ef-498d-a1b3-be2510c1f67c',
          title: '',
          description: '消息内容',
          label: '消息内容',
          keyName: 'msg',
          type: 'string',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '05ab1640-b558-4df2-ac29-71fc4071e6f2',
          title: '',
          description: '',
          label: '',
          keyName: 'success',
          type: 'boolean',
          params: [],
          examples: [],
          rules: { required: true },
        }, {
          id: '3adf6874-34d4-4fda-9be4-b72079c75d90',
          title: '',
          description: '时间戳',
          label: '时间戳',
          keyName: 'time',
          type: 'number',
          params: [],
          examples: [],
          rules: { required: true },
        }],
        examples: [],
        rules: { required: true },
      },
    }],
  }, {
    id: 'b75c07c2-8743-4a89-97ba-67646e2bdfe5',
    name: '未知分组',
    description: '未设置分组的接口集合',
    apiList: [],
  }],
};
