import { APIHelper } from '@api-helper/core/lib/types';

export const DOCUMENT: APIHelper.Document = {
  id: '9f6382dc-0b3f-4139-9691-4c2df8a52d9e',
  title: '接口文档',
  description: '测试API示例项目',
  version: '0.0.1-SNAPSHOT',
  documentVersion: '2.0',
  documentServerUrl: '',
  basePath: '/api',
  categoryList: [{
    id: '10a3c5a3-7a24-471a-a5d1-fffb2f2b2179',
    name: '宠物店认证模块',
    description: 'Tenant Controller',
    apiList: [{
      id: '12088870-e899-4110-87d8-26928a5d051b',
      title: '账户登录',
      description: '账户登录',
      label: '账户登录',
      docURL: '',
      path: '/api/{nickName}/auth',
      method: 'post',
      formDataKeyNameList: [],
      pathParamKeyNameList: [],
      queryStringKeyNameList: [],
      headers: null,
      cookies: null,
      requestContentType: [],
      responseContentType: [],
      requestDataSchema: {
        id: '1ace2cfb-1df8-4378-bead-738a14b19487',
        type: 'object',
        keyName: '',
        title: '',
        description: '',
        label: '',
        rules: { required: false },
        examples: [],
        params: [{
          id: '15a668a0-0386-42b1-ae5f-6ccb0bdd2965',
          type: 'string',
          keyName: 'code',
          title: '',
          description: '图形验证码结果',
          label: '图形验证码结果',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '58df4344-1378-4b53-86e4-a90cb9bc05d3',
          type: 'string',
          keyName: 'grant_type',
          title: '',
          description: '认证类型',
          label: '认证类型',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'a401503b-50cf-4f3b-b83a-e819fff8caa7',
          type: 'string',
          keyName: 'password',
          title: '',
          description: '密码密文(认证类型password必传)',
          label: '密码密文(认证类型password必传)',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '37f08ac9-477a-4d53-962d-1eac594c2a89',
          type: 'string',
          keyName: 'phone',
          title: '',
          description: '手机号',
          label: '手机号',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'cc01b864-06ca-4666-bf2a-b0f22d4f772b',
          type: 'string',
          keyName: 'scope',
          title: '',
          description: '授权范围，默认填all',
          label: '授权范围，默认填all',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '6f83218a-e92e-48b6-a65e-0c43e30921e1',
          type: 'string',
          keyName: 'smsCode',
          title: '',
          description: '短信验证码结果',
          label: '短信验证码结果',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '0d5ed712-3d94-4cda-8ba4-dd942f2995a0',
          type: 'string',
          keyName: 'tenantId',
          title: '',
          description: '登录机构ID',
          label: '登录机构ID',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '230ce29f-f647-4e28-926b-47c3a4ae507f',
          type: 'string',
          keyName: 'username',
          title: '',
          description: '账户名',
          label: '账户名',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'e17a4186-153e-4206-8d14-5327b5f5a8e6',
          type: 'string',
          keyName: 'uuid',
          title: '',
          description: '图形验证码key',
          label: '图形验证码key',
          rules: { required: false },
          examples: [],
          params: [],
          enum: [],
        }],
        enum: [],
      },
      requestExtraDataSchema: null,
      responseDataSchema: {
        id: '84174b6b-20dc-4d23-8cb5-2460df37ef75',
        type: 'object',
        keyName: '',
        title: '统一响应消息报文«TokenResponseVO»',
        description: '',
        label: '统一响应消息报文«TokenResponseVO»',
        rules: { required: true },
        examples: [],
        params: [{
          id: '32f8497d-86ce-4381-9c9a-754f5ecc24fe',
          type: 'number',
          keyName: 'code',
          title: '',
          description: '状态码',
          label: '状态码',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'b59253db-5a76-4191-8ae4-f52f045ea7df',
          type: 'object',
          keyName: 'data',
          title: 'TokenResponseVO',
          description: '业务数据',
          label: 'TokenResponseVO',
          rules: { required: true },
          examples: [],
          params: [{
            id: 'd278ee70-aeaa-42ab-ad39-0057a659e729',
            type: 'string',
            keyName: 'accessToken',
            title: '',
            description: '授权令牌',
            label: '授权令牌',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: 'de8c13ff-aed7-4503-b1f0-5fed89018aa9',
            type: 'number',
            keyName: 'currentTenant',
            title: '',
            description: '当前登录机构ID',
            label: '当前登录机构ID',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: 'ee56f59b-8c4d-423a-8593-db7f19d2d4da',
            type: 'string',
            keyName: 'nickName',
            title: '',
            description: '账户昵称',
            label: '账户昵称',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '960c3e99-6b1e-4858-a3c9-9d40dc81f1c7',
            type: 'array',
            keyName: 'permissions',
            title: '',
            description: '权限集合,登录成功返回',
            label: '权限集合,登录成功返回',
            rules: { required: true },
            examples: [],
            params: [{
              id: '183da691-f929-4c4d-8421-2da66e77a555',
              type: 'string',
              keyName: '',
              title: '',
              description: '',
              label: '',
              rules: { required: true },
              examples: [],
              params: [],
              enum: [],
            }],
            enum: [],
          }, {
            id: '6dd9cb6e-755e-4ed4-9817-47b748f3ebe8',
            type: 'string',
            keyName: 'submitToken',
            title: '',
            description: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            label: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '14b7c02c-92d2-4bb5-bafc-c7e5dfc40c89',
            type: 'array',
            keyName: 'tenants',
            title: '',
            description: '账户关联机构',
            label: '账户关联机构',
            rules: { required: true },
            examples: [],
            params: [{
              id: '47ffd0f6-31ba-4322-9f86-29fcf3cd6318',
              type: 'object',
              keyName: '',
              title: 'TenantBO',
              description: '',
              label: 'TenantBO',
              rules: { required: true },
              examples: [],
              params: [{
                id: '28cdfc5a-0d23-4eda-9524-c470cab9a2fe',
                type: 'number',
                keyName: 'id',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }, {
                id: 'ef08d44b-e1a6-4ae6-8575-f8b9433889a6',
                type: 'string',
                keyName: 'lastLoginTime',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }, {
                id: '61a653db-f8b8-49cd-a74f-3190f9bfd032',
                type: 'string',
                keyName: 'tenantCode',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }, {
                id: '450e8c90-3be2-4973-b2f0-b15ca3bc7471',
                type: 'string',
                keyName: 'tenantName',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }],
              enum: [],
            }],
            enum: [],
          }, {
            id: '5811c79e-d770-4aac-9099-b39f011895a3',
            type: 'number',
            keyName: 'type',
            title: '',
            description: '登录类型，1：账号密码，2：短信验证码',
            label: '登录类型，1：账号密码，2：短信验证码',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '644c3af6-ca62-47f0-a249-e39a96fe0444',
            type: 'number',
            keyName: 'userId',
            title: '',
            description: '账户ID',
            label: '账户ID',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '907b49ed-0627-41b0-9cb9-1b20361d3c79',
            type: 'number',
            keyName: 'userType',
            title: '',
            description: '账户类型，0：管理用户，1：机构用户',
            label: '账户类型，0：管理用户，1：机构用户',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: 'baa05696-2b8e-44d2-bb86-a237fa320da1',
            type: 'string',
            keyName: 'username',
            title: '',
            description: '账户名',
            label: '账户名',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }],
          enum: [],
        }, {
          id: '18b67056-7f2c-499c-b7de-2a953706b5bd',
          type: 'string',
          keyName: 'msg',
          title: '',
          description: '消息内容',
          label: '消息内容',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '4df9db9f-02b6-43a8-b90c-081b41b508e3',
          type: 'boolean',
          keyName: 'success',
          title: '',
          description: '',
          label: '',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '688b6a31-1e19-4aa1-9bd0-7db2da8301b2',
          type: 'number',
          keyName: 'time',
          title: '',
          description: '时间戳',
          label: '时间戳',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }],
        enum: [],
      },
    }, {
      id: '37ce4a0f-17a2-4b10-a9e5-9af8afb500d1',
      title: '登录确认',
      description: '登录确认',
      label: '登录确认',
      docURL: '',
      path: '/api/tenant/auth',
      method: 'get',
      formDataKeyNameList: [],
      pathParamKeyNameList: [],
      queryStringKeyNameList: ['tenantId', 'submitToken'],
      headers: null,
      cookies: null,
      requestContentType: [],
      responseContentType: [],
      requestDataSchema: {
        id: 'a7b79fe9-2277-4ada-9338-5f17600f0ef4',
        type: 'object',
        keyName: '',
        title: '',
        description: '',
        label: '',
        rules: { required: false },
        examples: [],
        params: [{
          id: 'a7da1b44-3187-4ca8-aee5-f7c50dc79d91',
          type: 'string',
          keyName: 'tenantId',
          title: '',
          description: '登录机构ID',
          label: '登录机构ID',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'dd47f6f2-1aca-4d4e-a589-32d89037fd82',
          type: 'string',
          keyName: 'submitToken',
          title: '',
          description: '登录确认令牌',
          label: '登录确认令牌',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }],
        enum: [],
      },
      requestExtraDataSchema: null,
      responseDataSchema: {
        id: '3a8bf792-a0b9-4b1e-9d2d-f6a18025ef95',
        type: 'object',
        keyName: '',
        title: '统一响应消息报文«TokenResponseVO»',
        description: '',
        label: '统一响应消息报文«TokenResponseVO»',
        rules: { required: true },
        examples: [],
        params: [{
          id: 'a430f8a7-e7ce-450e-89b1-2ffc82b89017',
          type: 'number',
          keyName: 'code',
          title: '',
          description: '状态码',
          label: '状态码',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '7cdf8ee0-4007-4ca5-947c-7504c3a508b0',
          type: 'object',
          keyName: 'data',
          title: 'TokenResponseVO',
          description: '业务数据',
          label: 'TokenResponseVO',
          rules: { required: true },
          examples: [],
          params: [{
            id: 'e57ab217-6e8c-456d-b95a-594bac4ef860',
            type: 'string',
            keyName: 'accessToken',
            title: '',
            description: '授权令牌',
            label: '授权令牌',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '0d036eb1-efe8-45d6-ae2d-120ae343bc1d',
            type: 'number',
            keyName: 'currentTenant',
            title: '',
            description: '当前登录机构ID',
            label: '当前登录机构ID',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: 'a822c553-81a4-4ce9-a6a9-b43d0d4df07a',
            type: 'string',
            keyName: 'nickName',
            title: '',
            description: '账户昵称',
            label: '账户昵称',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '3d309ae0-4897-41d5-aa13-545f543d10a1',
            type: 'array',
            keyName: 'permissions',
            title: '',
            description: '权限集合,登录成功返回',
            label: '权限集合,登录成功返回',
            rules: { required: true },
            examples: [],
            params: [{
              id: 'bd7d67aa-7def-4c79-bde6-4770ad39028b',
              type: 'string',
              keyName: '',
              title: '',
              description: '',
              label: '',
              rules: { required: true },
              examples: [],
              params: [],
              enum: [],
            }],
            enum: [],
          }, {
            id: 'b8bac009-6083-4f23-bea6-607d5be4a2d7',
            type: 'string',
            keyName: 'submitToken',
            title: '',
            description: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            label: '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '3b915725-99ff-40d1-a6a1-8186c9f8c0a0',
            type: 'array',
            keyName: 'tenants',
            title: '',
            description: '账户关联机构',
            label: '账户关联机构',
            rules: { required: true },
            examples: [],
            params: [{
              id: 'c9a49ec3-9eba-4e32-8204-c99ea2df9425',
              type: 'object',
              keyName: '',
              title: 'TenantBO',
              description: '',
              label: 'TenantBO',
              rules: { required: true },
              examples: [],
              params: [{
                id: 'cbe9bd40-5753-4965-a6a8-89b0de2ac316',
                type: 'number',
                keyName: 'id',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }, {
                id: '769ceef6-a58b-4d0d-b495-9c92c3373e1e',
                type: 'string',
                keyName: 'lastLoginTime',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }, {
                id: '2c5f3ee2-489a-4d39-9103-733c252b6e4a',
                type: 'string',
                keyName: 'tenantCode',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }, {
                id: '913d3b03-9b83-4f2f-af8f-82f62ed69f06',
                type: 'string',
                keyName: 'tenantName',
                title: '',
                description: '',
                label: '',
                rules: { required: true },
                examples: [],
                params: [],
                enum: [],
              }],
              enum: [],
            }],
            enum: [],
          }, {
            id: '7f42ef19-fc77-4ca7-80cd-7a31e26f4cf1',
            type: 'number',
            keyName: 'type',
            title: '',
            description: '登录类型，1：账号密码，2：短信验证码',
            label: '登录类型，1：账号密码，2：短信验证码',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: 'e82e55b1-66b0-4226-95bb-d7b4bad9558d',
            type: 'number',
            keyName: 'userId',
            title: '',
            description: '账户ID',
            label: '账户ID',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '6d759fa7-564c-426f-b53f-bf9fbb407f4f',
            type: 'number',
            keyName: 'userType',
            title: '',
            description: '账户类型，0：管理用户，1：机构用户',
            label: '账户类型，0：管理用户，1：机构用户',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }, {
            id: '1cda7dca-ba8f-4df0-9b80-e11ad03188ba',
            type: 'string',
            keyName: 'username',
            title: '',
            description: '账户名',
            label: '账户名',
            rules: { required: true },
            examples: [],
            params: [],
            enum: [],
          }],
          enum: [],
        }, {
          id: 'f861d35b-c984-4459-af59-eba5c5a5739f',
          type: 'string',
          keyName: 'msg',
          title: '',
          description: '消息内容',
          label: '消息内容',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '34f49d8a-c1d7-46b2-ae24-ca7f0e258f83',
          type: 'boolean',
          keyName: 'success',
          title: '',
          description: '',
          label: '',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'a622a2d7-5d01-481d-af74-801e18664e79',
          type: 'number',
          keyName: 'time',
          title: '',
          description: '时间戳',
          label: '时间戳',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }],
        enum: [],
      },
    }, {
      id: '1f0de7c1-097e-4e86-8f73-0d4ab930e34b',
      title: '手机验证码获取',
      description: '手机验证码获取',
      label: '手机验证码获取',
      docURL: '',
      path: '/api/tenant/auth/verification-code',
      method: 'get',
      formDataKeyNameList: [],
      pathParamKeyNameList: [],
      queryStringKeyNameList: ['code', 'phone', 'uuid'],
      headers: null,
      cookies: null,
      requestContentType: [],
      responseContentType: [],
      requestDataSchema: {
        id: 'd71dbebb-728d-449c-810a-c7ef187aa046',
        type: 'object',
        keyName: '',
        title: '',
        description: '',
        label: '',
        rules: { required: false },
        examples: [],
        params: [{
          id: 'b4f8235c-c174-4caf-bb05-5f1cf46c554a',
          type: 'string',
          keyName: 'code',
          title: '',
          description: '图形验证码值',
          label: '图形验证码值',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '577c3496-f581-429f-a751-3fa1d855b225',
          type: 'string',
          keyName: 'phone',
          title: '',
          description: '手机号',
          label: '手机号',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '900492ee-0861-4b8f-a847-7608b4ecfa02',
          type: 'string',
          keyName: 'uuid',
          title: '',
          description: '图形验证码ID',
          label: '图形验证码ID',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }],
        enum: [],
      },
      requestExtraDataSchema: null,
      responseDataSchema: {
        id: '86506a21-655a-4415-82b1-7ea9eaa9135d',
        type: 'object',
        keyName: '',
        title: '统一响应消息报文«Void»',
        description: '',
        label: '统一响应消息报文«Void»',
        rules: { required: true },
        examples: [],
        params: [{
          id: 'e1a3e8f9-1340-406c-bd21-874b9cc1e45d',
          type: 'number',
          keyName: 'code',
          title: '',
          description: '状态码',
          label: '状态码',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '78f94146-a431-4910-ae2e-897891b2f4c9',
          type: 'string',
          keyName: 'msg',
          title: '',
          description: '消息内容',
          label: '消息内容',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: '48b9cfa8-4f9b-4687-a244-c271ec5ad8fb',
          type: 'boolean',
          keyName: 'success',
          title: '',
          description: '',
          label: '',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }, {
          id: 'c5cc10bd-e901-4501-96e8-01ad936ab15b',
          type: 'number',
          keyName: 'time',
          title: '',
          description: '时间戳',
          label: '时间戳',
          rules: { required: true },
          examples: [],
          params: [],
          enum: [],
        }],
        enum: [],
      },
    }],
  }, {
    id: '8462f968-63aa-4b77-a7d4-581e7452e7fd',
    name: '未知分组',
    description: '未设置分组的接口集合',
    apiList: [],
  }],
};
