/* eslint-disable */
import { APIHelper } from '@api-helper/core/es/lib/types';

export const DOCUMENT = {
  'id': '8f680b48-33a7-49c0-8824-12c7be46e1c1',
  'title': '接口文档',
  'description': '测试API示例项目',
  'version': '0.0.1-SNAPSHOT',
  'openapiVersion': '2.0',
  'basePath': '/api',
  'categoryList': [{
    'id': '8c0b4e07-8cb5-42d1-acdd-823d6ac9cfbe',
    'name': '宠物店认证模块',
    'description': 'Tenant Controller',
    'apiList': [{
      'id': '51b3b94e-9d2a-4341-9a53-af0805a9b940',
      'title': '账户登录',
      'description': '账户登录',
      'label': '账户登录',
      'path': '/api/tenant/auth',
      'method': 'post',
      'formDataKeyNameList': [],
      'pathParamKeyNameList': [],
      'queryStringKeyNameList': [],
      'requestDataSchema': {
        'type': 'object',
        'params': [{
          'id': '65d26cb2-dd20-4b0d-8672-97dc87945155',
          'title': '',
          'description': '图形验证码结果',
          'keyName': 'code',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '44536ff2-c121-432d-bf5b-7a6ad080ff77',
          'title': '',
          'description': '认证类型',
          'keyName': 'grant_type',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '03bc3036-69f6-4633-b17c-50099c90794a',
          'title': '',
          'description': '密码密文(认证类型password必传)',
          'keyName': 'password',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '62ab57a0-4abc-4db8-923c-275642daab2f',
          'title': '',
          'description': '手机号',
          'keyName': 'phone',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '97c76e0e-f485-47dd-abeb-e8c4d44a6ae7',
          'title': '',
          'description': '授权范围，默认填all',
          'keyName': 'scope',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '6c4a4e45-e4ce-4562-9e42-94d168757630',
          'title': '',
          'description': '短信验证码结果',
          'keyName': 'smsCode',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '7a13954a-6160-4560-83b8-a33ab868e043',
          'title': '',
          'description': '登录机构ID',
          'keyName': 'tenantId',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '3507c55b-81db-418b-ab97-ed1276624be5',
          'title': '',
          'description': '账户名',
          'keyName': 'username',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '6b910879-b66d-4f2c-92dc-fb535c549c31',
          'title': '',
          'description': '图形验证码key',
          'keyName': 'uuid',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }],
      },
      'requestExtraDataSchema': null,
      'responseDataSchema': {
        'id': '80b46b59-81d7-4bbf-9462-89f940955803',
        'title': '统一响应消息报文«TokenResponseVO»',
        'description': '',
        'keyName': '',
        'type': 'object',
        'params': [{
          'id': 'bfb9b272-257e-401c-8647-3edf269e5d28',
          'title': '',
          'description': '状态码',
          'keyName': 'code',
          'type': 'number',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }, {
          'id': '004303e9-1a6a-47ca-a5db-121261e150da',
          'title': 'TokenResponseVO',
          'description': '业务数据',
          'keyName': 'data',
          'type': 'object',
          'params': [{
            'id': '073650be-55cf-409d-bf72-e9bd265aafda',
            'title': '',
            'description': '授权令牌',
            'keyName': 'accessToken',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '708299a5-42e4-4221-8274-333534bb13b2',
            'title': '',
            'description': '当前登录机构ID',
            'keyName': 'currentTenant',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '2f22580e-7644-4734-bd3f-00fd8d12dd5a',
            'title': '',
            'description': '账户昵称',
            'keyName': 'nickName',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '7a89327a-77fe-420d-8aea-c71a4c4bec62',
            'title': '',
            'description': '权限集合,登录成功返回',
            'keyName': 'permissions',
            'type': 'array',
            'params': [{
              'id': 'dba3fff2-71e0-47c8-9691-732ea1dcd05a',
              'title': '',
              'description': '',
              'keyName': '',
              'type': 'string',
              'params': [],
              'examples': [],
              'rules': {'required': false},
            }],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '175ea16b-4108-4907-9e4f-06212c4fcc7f',
            'title': '',
            'description': '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            'keyName': 'submitToken',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '23725480-86b7-4fb7-be63-1710f816b7a8',
            'title': '',
            'description': '账户关联机构',
            'keyName': 'tenants',
            'type': 'array',
            'params': [{
              'id': '2879a880-77fd-4c49-a178-a20a37b9b438',
              'title': 'TenantBO',
              'description': '',
              'keyName': '',
              'type': 'object',
              'params': [{
                'id': 'c4a7b302-a412-43b7-a14b-d9fbc3b595a1',
                'title': '',
                'description': '',
                'keyName': 'id',
                'type': 'number',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }, {
                'id': '14eb7a3a-2fde-4e18-ae97-5aa207e94e05',
                'title': '',
                'description': '',
                'keyName': 'lastLoginTime',
                'type': 'string',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }, {
                'id': '7994a1f1-49d4-408b-ade4-9309fe03d889',
                'title': '',
                'description': '',
                'keyName': 'tenantCode',
                'type': 'string',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }, {
                'id': 'd7495f01-49b3-49ca-be8d-ddf833d32392',
                'title': '',
                'description': '',
                'keyName': 'tenantName',
                'type': 'string',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }],
              'examples': [],
              'rules': {'required': false},
            }],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': 'ab381d37-1e18-4920-80e1-7053bb6df7de',
            'title': '',
            'description': '登录类型，1：账号密码，2：短信验证码',
            'keyName': 'type',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': 'e423e648-ffe2-43b5-8e93-8a746d8f9537',
            'title': '',
            'description': '账户ID',
            'keyName': 'userId',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '1b74a5e3-2f5a-44c8-b77a-73b601f6c023',
            'title': '',
            'description': '账户类型，0：管理用户，1：机构用户',
            'keyName': 'userType',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '629e7666-59a8-4ba0-b963-a01cb6e8b004',
            'title': '',
            'description': '账户名',
            'keyName': 'username',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': 'd6cdd3ad-3ec8-42c0-a939-fba05195b494',
          'title': '',
          'description': '消息内容',
          'keyName': 'msg',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }, {
          'id': 'd963ac2f-7a9a-422e-af13-9f7a5fc61803',
          'title': '',
          'description': '',
          'keyName': 'success',
          'type': 'boolean',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '5befe191-c67e-45ec-8a13-61d422660a45',
          'title': '',
          'description': '时间戳',
          'keyName': 'time',
          'type': 'number',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }],
        'examples': [],
        'rules': {'required': false},
      },
    }, {
      'id': 'd9e3e423-191e-4cce-ac4a-a56c8b8e09dc',
      'title': '登录确认',
      'description': '登录确认',
      'label': '登录确认',
      'path': '/api/tenant/auth',
      'method': 'get',
      'formDataKeyNameList': [],
      'pathParamKeyNameList': [],
      'queryStringKeyNameList': ['tenantId', 'submitToken'],
      'requestDataSchema': {
        'type': 'object',
        'params': [{
          'examples': [],
          'id': '0fea28c3-7341-4b49-a5f0-ca1cef1b7f88',
          'title': '',
          'description': '登录机构ID',
          'keyName': 'tenantId',
          'type': 'string',
          'params': [],
          'rules': {'required': true},
        }, {
          'examples': [],
          'id': 'e9b0214a-0526-4909-8eb9-ffaf5c03edec',
          'title': '',
          'description': '登录确认令牌',
          'keyName': 'submitToken',
          'type': 'string',
          'params': [],
          'rules': {'required': true},
        }],
      },
      'requestExtraDataSchema': null,
      'responseDataSchema': {
        'id': '8d9d5fa8-fa1c-4134-a38e-500fd905eb53',
        'title': '统一响应消息报文«TokenResponseVO»',
        'description': '',
        'keyName': '',
        'type': 'object',
        'params': [{
          'id': '0818aebb-e18f-4813-bf8f-3eadc42ec857',
          'title': '',
          'description': '状态码',
          'keyName': 'code',
          'type': 'number',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }, {
          'id': 'e07e5e8e-f3f7-4fae-8bbb-a8f2560e683c',
          'title': 'TokenResponseVO',
          'description': '业务数据',
          'keyName': 'data',
          'type': 'object',
          'params': [{
            'id': 'f5bc039d-4cb6-4961-9837-ba6b7af75b41',
            'title': '',
            'description': '授权令牌',
            'keyName': 'accessToken',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': 'e8639573-125d-478f-9fc4-1e6dcc472ece',
            'title': '',
            'description': '当前登录机构ID',
            'keyName': 'currentTenant',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '886392e2-63d9-4393-94d7-4cfe7ba3a3fa',
            'title': '',
            'description': '账户昵称',
            'keyName': 'nickName',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': 'e177a26e-bdd4-4118-9807-4a68fbe40d02',
            'title': '',
            'description': '权限集合,登录成功返回',
            'keyName': 'permissions',
            'type': 'array',
            'params': [{
              'id': '1ef96b58-3396-47e9-8b20-84dd1137fa92',
              'title': '',
              'description': '',
              'keyName': '',
              'type': 'string',
              'params': [],
              'examples': [],
              'rules': {'required': false},
            }],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '2d866ec6-5fd2-47bf-ad2d-064a254ec35f',
            'title': '',
            'description': '登录确认令牌，若存在多机构不直接返回accessToken，通过SubmitToken确认登录机构',
            'keyName': 'submitToken',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '72b0996c-dcab-4727-a8ab-ebb3435cb52f',
            'title': '',
            'description': '账户关联机构',
            'keyName': 'tenants',
            'type': 'array',
            'params': [{
              'id': 'f8266c15-6eb1-4e00-9bdf-a125a05f2bdf',
              'title': 'TenantBO',
              'description': '',
              'keyName': '',
              'type': 'object',
              'params': [{
                'id': '3f388023-bde7-47c0-a1ff-418dac7ba9d7',
                'title': '',
                'description': '',
                'keyName': 'id',
                'type': 'number',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }, {
                'id': 'fb5c77e1-146e-4fbc-a313-f454b25e0d51',
                'title': '',
                'description': '',
                'keyName': 'lastLoginTime',
                'type': 'string',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }, {
                'id': 'c219971c-d96d-4ffb-9e1e-a30d7fbd5fec',
                'title': '',
                'description': '',
                'keyName': 'tenantCode',
                'type': 'string',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }, {
                'id': '56228e76-10b1-41f4-b130-df2f64d63b7b',
                'title': '',
                'description': '',
                'keyName': 'tenantName',
                'type': 'string',
                'params': [],
                'examples': [],
                'rules': {'required': false},
              }],
              'examples': [],
              'rules': {'required': false},
            }],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '3409533d-1583-4117-9f4c-875d2f5523c3',
            'title': '',
            'description': '登录类型，1：账号密码，2：短信验证码',
            'keyName': 'type',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '2cb0e3fd-c3da-4e39-8328-9c92668c3d8c',
            'title': '',
            'description': '账户ID',
            'keyName': 'userId',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': '2e1b15dd-ec3c-43a3-b7c2-62229c9e7da7',
            'title': '',
            'description': '账户类型，0：管理用户，1：机构用户',
            'keyName': 'userType',
            'type': 'number',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }, {
            'id': 'd9f61744-edab-4d88-89ad-39364dc2260b',
            'title': '',
            'description': '账户名',
            'keyName': 'username',
            'type': 'string',
            'params': [],
            'examples': [],
            'rules': {'required': false},
          }],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '30f4f1ad-3fc8-461b-955c-0f4972424f17',
          'title': '',
          'description': '消息内容',
          'keyName': 'msg',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }, {
          'id': 'c930c624-70bc-4ec8-a1ce-19d96c200889',
          'title': '',
          'description': '',
          'keyName': 'success',
          'type': 'boolean',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '5e1488d2-a4c0-4de4-9a01-b28f27df09a1',
          'title': '',
          'description': '时间戳',
          'keyName': 'time',
          'type': 'number',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }],
        'examples': [],
        'rules': {'required': false},
      },
    }, {
      'id': '832b91f9-43e0-423b-8c9b-4475dde98fc5',
      'title': '手机验证码获取',
      'description': '手机验证码获取',
      'label': '手机验证码获取',
      'path': '/api/tenant/auth/verification-code',
      'method': 'get',
      'formDataKeyNameList': [],
      'pathParamKeyNameList': [],
      'queryStringKeyNameList': ['code', 'phone', 'uuid'],
      'requestDataSchema': {
        'type': 'object',
        'params': [{
          'examples': [],
          'id': '49cb9077-0972-48af-80e0-a95ae7cc4bc6',
          'title': '',
          'description': '图形验证码值',
          'keyName': 'code',
          'type': 'string',
          'params': [],
          'rules': {'required': true},
        }, {
          'examples': [],
          'id': '78a85614-b25d-4f7a-9934-97c37c397589',
          'title': '',
          'description': '手机号',
          'keyName': 'phone',
          'type': 'string',
          'params': [],
          'rules': {'required': true},
        }, {
          'examples': [],
          'id': '9869c9ad-8efa-4983-b7f6-82f9e60d5264',
          'title': '',
          'description': '图形验证码ID',
          'keyName': 'uuid',
          'type': 'string',
          'params': [],
          'rules': {'required': true},
        }],
      },
      'requestExtraDataSchema': null,
      'responseDataSchema': {
        'id': 'b2e3370a-6a6d-41b4-bab4-8f03ba943e48',
        'title': '统一响应消息报文«Void»',
        'description': '',
        'keyName': '',
        'type': 'object',
        'params': [{
          'id': 'a51c2867-2709-4fc5-a396-5e265b4072c1',
          'title': '',
          'description': '状态码',
          'keyName': 'code',
          'type': 'number',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }, {
          'id': 'e6536b16-8e7f-47ff-84e5-f497767a217b',
          'title': '',
          'description': '消息内容',
          'keyName': 'msg',
          'type': 'string',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }, {
          'id': 'f899ee50-99c3-4127-acde-8ee814cd77d3',
          'title': '',
          'description': '',
          'keyName': 'success',
          'type': 'boolean',
          'params': [],
          'examples': [],
          'rules': {'required': false},
        }, {
          'id': '01e669ea-3b0d-48f3-9535-ded4b4bae60e',
          'title': '',
          'description': '时间戳',
          'keyName': 'time',
          'type': 'number',
          'params': [],
          'examples': [],
          'rules': {'required': true},
        }],
        'examples': [],
        'rules': {'required': false},
      },
    }],
  }, {
    'id': 'c3e3bc44-6ab2-4365-b2c9-3f56671e1f36',
    'name': '未知分组',
    'description': '没有设置分组的接口集合',
    'apiList': [],
  }],
} as unknown as APIHelper.Document;
